# Generated by Django 2.2.1 on 2019-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
