# Generated by Django 2.2.1 on 2019-05-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_address1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address1',
        ),
    ]
