# Generated by Django 2.2.1 on 2019-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_parameter_person_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_information',
            name='waiting_time',
            field=models.IntegerField(default=0.0),
        ),
    ]
