# Generated by Django 2.2.1 on 2019-05-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number', models.IntegerField(default=0)),
                ('timeout', models.IntegerField(default=0.0)),
                ('skip_probability', models.FloatField(default=0.0)),
                ('arrive_time', models.IntegerField(default=0)),
                ('average_dining_time', models.IntegerField(default=0)),
                ('table_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='person_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ID_number', models.CharField(blank=True, max_length=50)),
                ('place', models.IntegerField(default=0)),
                ('waiting_time', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('is_spicy', models.BooleanField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wait.Restaurant')),
            ],
        ),
    ]
