# Generated by Django 2.2.1 on 2019-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='timeout',
            field=models.IntegerField(default=0.0),
        ),
    ]
